# Generated by Django 5.0.1 on 2024-01-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='Adres')),
                ('user', models.CharField(max_length=500, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(max_length=500, verbose_name='Şifre')),
            ],
        ),
    ]
